### PR TITLE
Branch edit command

### PR DESCRIPTION
**Pull request by kanna-1**

### CODE REVIEW

**Comment by kanna-1** [comment]
Still a WIP, also wanted to check CI  :)

Known Issues:
1. Unable to edit based on id.
2. Unable to edit multiple tags / medical history (i.e. can only add one).
3. Haven't consider the case where user enters both id and name.

**Comment by kanna-1** [comment]
Issue 1 and 3 has been fixed. Will keep issue 2 in view.

Requesting peer reviewers for merging.

**Comment by kanna-1** [comment]
Requesting reviewers.

**Review by hyc17003 — COMMENTED** [review]
LGTM!

**Pull request merged**
