### PR TITLE
GUI branch

### PR DESCRIPTION
**Pull request by WeeeHung**
- Edit Command Box Text Field's placeholder text to prompt users to hit `spacebar`
- application listens for the event when `spacebar` is pressed

When this event happens:
1. focus of application will be on the Command Box Text Field.

### CODE REVIEW

**Comment by WeeeHung** [comment]
Once again, codecov/patch failed as more functions were added under UI java files. Team has decided to not do automated testing for GUI related code.

**Comment by WeeeHung** [comment]
Screenshot below shows the new placeholder for the Text Field. On press of spacebar, user will be able to type straight to the textfield without the use of _additional mouse clicking_

image

**Comment by WeeeHung** [comment]
Header Label is changed to something more generic compared to the previous `Hi {user} :)`. This is due to the time constraint in implementing the intended settings configuration for users to personalize their application.

**Comment by WZWren** [comment]
This looks good. Merging.

**Pull request merged**
