### PR TITLE
Remove all traces of tag in the code base

### PR DESCRIPTION
**Pull request by kanna-1**
This PR effectively remove **ALL** traces of tags in the code base.

### CODE REVIEW

**Comment by kanna-1** [comment]
I do not think it is possible to test SampleDataUtil.java

**Comment by WZWren** [comment]
@kanna-1, there seems to be some checkstyle issues preventing the CI from running.

**Review by nubnubyas — COMMENTED** [review]
Good Job on removing most of the references for tags. However, I think there are still some references to Tag in other files, here are the files:

1. ModelClassDiagram.puml
2. StorageClassDiagram.puml
3. AddRemark.md
4. TracindCode.md
5. PersonCard.java

Most of the it does not affect how the program runs, you can take a look through of it and decide whether to remove.

**Comment by kanna-1** [comment]
> Good Job on removing most of the references for tags. However, I think there are still some references to Tag in other files, here are the files:
> 
> 1. ModelClassDiagram.puml
> 2. StorageClassDiagram.puml
> 3. AddRemark.md
> 4. TracindCode.md
> 5. PersonCard.java
> 
> Most of the it does not affect how the program runs, you can take a look through of it and decide whether to remove.

Good catch on the PersonCard.java. I will remove accordingly. However, I will not edit the .md and .puml files since there is a need to refactor the whole file to match to our current application.

**Comment by WZWren** [comment]
@kanna-1 I have converted your PR to a Draft PR in case we accidentally merge it - your test cases are failing to compile.
```
/home/runner/work/tp/tp/src/test/java/seedu/address/testutil/TypicalPersons.java:48: error: illegal start of type
```
Here is the basic error log from the CI. On `Line 48` of the particular file, you've left a hanging period.

**Comment by kanna-1** [comment]
> @kanna-1 I have converted your PR to a Draft PR in case we accidentally merge it - your test cases are failing to compile.
> 
> ```
> /home/runner/work/tp/tp/src/test/java/seedu/address/testutil/TypicalPersons.java:48: error: illegal start of type
> ```
> 
> Here is the basic error log from the CI. On `Line 48` of the particular file, you've left a hanging period.

Oh my bad. It must have been after handling the merge conflict.

**Comment by WZWren** [comment]
This looks good. Hopefully there isn't any other references to `Tag` that we may have missed.

As mentioned above, `SampleDataUtil` is a portion of the code that we have agreed to not test, so we will ignore the reduced codecov resulting from this change.

**Comment by WZWren** [comment]
I will merge this branch into the `master` branch now. 

> Good catch on the PersonCard.java. I will remove accordingly. However, I will not edit the .md and .puml files since there is a need to refactor the whole file to match to our current application.

Regarding this point made by @kanna-1, I will open an issue as a reminder to fix this by v1.4.

**Pull request merged**
