### PR TITLE
Update app logo

### PR DESCRIPTION
**Pull request by kanna-1**
This PR changes the logo of the app.

### CODE REVIEW

**Comment by WZWren** [comment]
Can we get a screenshot of how this icon looks on the app?

**Comment by kanna-1** [comment]
Yes. Here is a snapshot.

Screenshot (236)

**Comment by nubnubyas** [comment]
LGTM

**Comment by WeeeHung** [comment]
Closed the pull request by accident. Anyways logo looks good to me, merging.

**Pull request merged**
